services:
  postgres:
    image: postgres:latest
    container_name: postgres-tpch
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tpch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./tpch_api
      dockerfile: Dockerfile
    container_name: tpch-api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/tpch
    depends_on:
      - postgres

volumes:
  postgres_data: